[tool.poetry]
name = "TinyCTA"
version = "0.0.0"
description = "..."
authors = ["Thomas Schmelzer"]
readme = "README.md"
repository = "https://github.com/tschm/TinyCTA"
packages = [{include = "tinycta"}]

[tool.poetry.dependencies]
python = ">=3.9.0,<4.0"
pandas = "*"
QuantStats = "*"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pytest-cov = "*"
mock = "*"

[tool.poetry.group.jupyter.dependencies]
jupyterlab = "*"
jupyter-book = "0.15.1"
pyyaml = "6.0"

[tool.peotry.group.linting.dependencies]
pylint = "*"
ruff = "0.0.277"
pre-commit = "*"
black = "23.3.0"

[tool.poetry.group.dev.dependencies]
yfinance = "*"
plotly = "*"
cvxpy = "*"
loguru = "*"

[build-system]
requires = ["poetry>=1.0.2"]
build-backend = "poetry.masonry.api"
